var lookup = {
    'COMMAND_NOT_FOUND' : 'Command not found, type ^3#help^7 for a list of commands',
    'COMMAND_ARGUMENT_ERROR' : 'Not enough arguments supplied',
    'COMMAND_CLIENT_NOT_FOUND' : 'Player not found',
    'COMMAND_CLIENT_NOT_INGAME' : 'Player is not in game',
    'ROLE_HIERARCHY_ERROR' : 'You can\'t set that role',
    'CLIENT_HIERARCHY_ERROR': 'You cannot execute this on that client',
    'COMMAND_EXECUTE_SUCCESS' : 'Command executed successfully',
    'ROLE_SELF_ERROR' : 'You can\'t set your own role',
    'COMMAND_STATS_FORMAT' : '[ ^5%NAME% ^7] => ^5%KILLS%^7 Kills | ^5%DEATHS% ^7Deaths | ^5%KDR% ^7KDR | ^5%PERFORMANCE%^7 Performance | ^7Play time ^5%PLAYEDTIME%',
    'COMMAND_FORBIDDEN' : 'You don\'t have enough permissions for this',
    'ROLE_NOT_EXIST' : 'Specified role doesn\'t exist',
    'COMMAND_HELP': 'Display the list of commands',
    'COMMAND_PING': 'Pings the server',
    'COMMAND_TP' : 'Teleport to player',
    'COMMAND_TPHERE' : 'Teleport player to you',
    'COMMAND_SETROLE' : 'Set player\'s role',
    'COMMAND_RCON' : 'Execute rcon commands',
    'COMMAND_STATS': 'Returns your stats',
    'COMMAND_OWNER': 'Claim ownership of a server',
    'COMMAND_KICK': 'Kick a player, usage: kick <ClientId>',
    'COMMAND_FIND': 'Find a players\'s ID',
    'COMMAND_INFO': 'Get NSM info',
    'COMMAND_TOKEN_FORMAT': 'Your login token is %TOKEN%, valid for 2 minutes, your ClientID is ^2%CLIENTID%^7 { ^5numbers^7, ^3letters^7 }',
    'COMMAND_PARSE_TIME_ERROR': 'Could not parse time, format: 1d (day), 2h (hours), 3m (mins), 10s (secs)',
    'RCON_SERVER_NOT_SPECIFIED': 'Please specify the server to execute this command on',
    'SERVER_NOT_EXIST': 'Specified server doesn\'t exist or is offline, Usage: rcon serverid command'
}